version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - run: node --version
      - run: npm install
      - run: npm run semantic-release

workflows:
  test_and_release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - auto-bump-test
