module.exports = [
  {
    id: 'performance',
    label: 'Performance',
    color: '#fff',
    bgColor: '#17d406',
    description: 'Boosting perfomance of web pages, rising efficiency and gaining control over page loading.',
  },
  {
    id: 'javascript',
    label: 'Javascript',
    color: '#000',
    bgColor: '#feec4e',
    description: '',
  },
  {
    id: 'typescript',
    label: 'Typescript',
    color: '#fff',
    bgColor: '#367ac4',
    description: '',
  },
  {
    id: 'react',
    label: 'React',
    color: '#000',
    bgColor: '#67dbf9',
    description: '',
  },
  {
    id: 'redux',
    label: 'Redux',
    color: '#fff',
    bgColor: '#764eba',
    description: '',
  },
  {
    id: 'algorithms',
    label: 'Algorithms',
    color: '#fff',
    bgColor: '#0500ff',
    description: '',
  },
  {
    id: 'html',
    label: 'HTML',
    color: '#fff',
    bgColor: '#353535',
    description: '',
  },
  {
    id: 'css',
    label: 'CSS',
    color: '#fff',
    bgColor: '#ee3232',
    description: '',
  },
  {
    id: 'authorization',
    label: 'Authorization',
    color: '#fff',
    bgColor: '#460ac6',
    description: '',
  },
  {
    id: 'browsers',
    label: 'Browsers',
    color: '#000',
    bgColor: '#58f2bb',
    description: '',
  },
  {
    id: 'cicd',
    label: 'CI/CD',
    color: '#fff',
    bgColor: '#ffc226',
    description: '',
  },
]
